trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  displayName: 'Restore NuGet'
  inputs:
    restoreSolution: '**/*.sln'
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
